### ISSUE TITLE
Navbar  link qimirlayabdi

### ISSUE THREAD

**Issue by nameal010203** [Sardor0795/Apple-watch#1]
![image](https://user-images.githubusercontent.com/105722979/168846352-f3653e14-e9b1-4679-9aa8-da122d534f2c.png)
navbar hover bolganda siljish hosil bolyabdi shuni yoqotish kerak

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/169435639-e6a4258c-1872-4638-837d-a7b5c1850188.png)

To'g'irlandi!!!
