### ISSUE TITLE
brand section  background berish

### ISSUE THREAD

**Issue by nameal010203** [Sardor0795/Apple-watch#3]
![image](https://user-images.githubusercontent.com/105722979/168848818-891fdb8d-ad7a-4c33-83ff-729e79bbf26a.pngbac
background  dagi rasm olchami hato berilgan

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/169441257-13e2b2ea-8bb4-475e-8f75-4dac699f0884.png)

To'g'irlandi!!!
