### ISSUE TITLE
Header logo 

### ISSUE THREAD

**Issue by nameal010203** [Sardor0795/Apple-watch#4]
![image](https://user-images.githubusercontent.com/105722979/168849820-5a2da110-4eee-42a3-b722-7952db632d49.png)
logo nisbatan qisilib qolgan , imgni orab turgan a ga display flex berib qoying

**Comment by Sardor0795** [comment]
![image](https://user-images.githubusercontent.com/87645525/169436813-8135ada0-7e93-49d1-9cd0-f06e767c984a.png)
